# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GraficohGUCJk.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTextBrowser, QWidget)
import recursos_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(657, 608)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(570, 20, 41, 31))
        self.label.setPixmap(QPixmap(u":/Iconos/HPH.svg"))
        self.label.setScaledContents(True)
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(30, 200, 591, 351))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(420, 20, 121, 41))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(420, 130, 121, 41))
        self.junta1 = QLabel(self.centralwidget)
        self.junta1.setObjectName(u"junta1")
        self.junta1.setGeometry(QRect(20, 10, 49, 16))
        font = QFont()
        font.setFamilies([u"Swis721 BlkCn BT"])
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.junta1.setFont(font)
        self.junta2 = QLabel(self.centralwidget)
        self.junta2.setObjectName(u"junta2")
        self.junta2.setGeometry(QRect(20, 40, 49, 16))
        self.junta2.setFont(font)
        self.junta3 = QLabel(self.centralwidget)
        self.junta3.setObjectName(u"junta3")
        self.junta3.setGeometry(QRect(20, 70, 49, 16))
        self.junta3.setFont(font)
        self.junta4 = QLabel(self.centralwidget)
        self.junta4.setObjectName(u"junta4")
        self.junta4.setGeometry(QRect(20, 100, 49, 16))
        self.junta4.setFont(font)
        self.junta5 = QLabel(self.centralwidget)
        self.junta5.setObjectName(u"junta5")
        self.junta5.setGeometry(QRect(20, 130, 49, 16))
        self.junta5.setFont(font)
        self.junta6 = QLabel(self.centralwidget)
        self.junta6.setObjectName(u"junta6")
        self.junta6.setGeometry(QRect(20, 160, 49, 16))
        self.junta6.setFont(font)
        self.ValorJ1 = QLabel(self.centralwidget)
        self.ValorJ1.setObjectName(u"ValorJ1")
        self.ValorJ1.setGeometry(QRect(80, 10, 111, 16))
        font1 = QFont()
        font1.setFamilies([u"Swis721 BlkCn BT"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.ValorJ1.setFont(font1)
        self.ValorJ2 = QLabel(self.centralwidget)
        self.ValorJ2.setObjectName(u"ValorJ2")
        self.ValorJ2.setGeometry(QRect(80, 40, 111, 16))
        self.ValorJ2.setFont(font1)
        self.ValorJ3 = QLabel(self.centralwidget)
        self.ValorJ3.setObjectName(u"ValorJ3")
        self.ValorJ3.setGeometry(QRect(80, 70, 111, 16))
        self.ValorJ3.setFont(font1)
        self.ValorJ4 = QLabel(self.centralwidget)
        self.ValorJ4.setObjectName(u"ValorJ4")
        self.ValorJ4.setGeometry(QRect(80, 100, 111, 16))
        self.ValorJ4.setFont(font1)
        self.ValorJ5 = QLabel(self.centralwidget)
        self.ValorJ5.setObjectName(u"ValorJ5")
        self.ValorJ5.setGeometry(QRect(80, 130, 111, 16))
        self.ValorJ5.setFont(font1)
        self.ValorJ6 = QLabel(self.centralwidget)
        self.ValorJ6.setObjectName(u"ValorJ6")
        self.ValorJ6.setGeometry(QRect(80, 160, 111, 16))
        self.ValorJ6.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(210, 10, 161, 16))
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(210, 40, 141, 16))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 70, 141, 16))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(210, 100, 161, 16))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(210, 130, 151, 16))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(210, 160, 151, 16))
        self.label_7.setFont(font1)
        self.Absoluto = QRadioButton(self.centralwidget)
        self.Absoluto.setObjectName(u"Absoluto")
        self.Absoluto.setGeometry(QRect(440, 70, 89, 20))
        self.radioButton_2 = QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(440, 100, 89, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 657, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Encender", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Reiniciar Posici\u00f3n", None))
        self.junta1.setText(QCoreApplication.translate("MainWindow", u"Junta 1", None))
        self.junta2.setText(QCoreApplication.translate("MainWindow", u"Junta 2", None))
        self.junta3.setText(QCoreApplication.translate("MainWindow", u"Junta 3", None))
        self.junta4.setText(QCoreApplication.translate("MainWindow", u"Junta 4", None))
        self.junta5.setText(QCoreApplication.translate("MainWindow", u"Junta 5", None))
        self.junta6.setText(QCoreApplication.translate("MainWindow", u"Junta 6", None))
        self.ValorJ1.setText("")
        self.ValorJ2.setText("")
        self.ValorJ3.setText("")
        self.ValorJ4.setText("")
        self.ValorJ5.setText("")
        self.ValorJ6.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [-3, 150.0]", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [-120.0, 0.0]", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [0.0, 150.0]", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [-135.0, 135.0]", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [-120.0, 120.0]", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"[Max Min] : [-160.0, 160.0]", None))
        self.Absoluto.setText(QCoreApplication.translate("MainWindow", u"Absoluto", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"Relativo", None))
    # retranslateUi

